# [Meida State]
UNKNOWN_MEDIA_STATUS = 0
NO_MEDIA = 1
LOADING_MEDIA = 2
LOADED_MEDIA = 3
STALLED_MEDIA = 4
BUFFERING_MEDIA = 5
BUFFERED_MEDIA = 6
END_OF_MEDIA = 7
INVALID_MEDIA = 8

# [Player State]
PLAYER_STATE_STOP = 0
PLAYER_STATE_PLAY = 1
PLAYER_STATE_PAUSE = 2